# -*- coding: utf-8 -*-
"""app.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1-Tk1w99Scv_3gclhgnCE4kboiFJHO_d0
"""

import streamlit as st
import pandas as pd
import matplotlib.pyplot as plt

# ======================
# LOAD DATA
# ======================

@st.cache_data
def load_data():
    detections = pd.read_csv("detections_with_phase.csv")
    migration_summary = pd.read_csv("migration_phase_summary.csv")
    phase_summary = pd.read_csv("phase_summary_XAI.csv")
    return detections, migration_summary, phase_summary

detections, migration_summary, phase_summary = load_data()

# Sidebar – tag selector
all_tags = sorted(detections["Tag"].unique())
selected_tag = st.sidebar.selectbox("Select Tag", all_tags)

# Sidebar – page selector
page = st.sidebar.radio("Navigation", ["Home", "EDA", "Model", "XAI"])

# ======================
# HOME PAGE
# ======================

if page == "Home":
    st.title("Owl Migration Pattern App")
    st.write("""
    This app shows:
    - EDA (exploratory analysis)
    - DBSCAN-based migration modeling
    - XAI (Explainable AI) analysis

    All data is taken from Motus detections for each owl tag.
    """)

# ======================
# EDA PAGE
# ======================

elif page == "EDA":
    st.title("Exploratory Data Analysis")

    st.write("### Migration Summary (all tags)")
    st.dataframe(migration_summary)

    st.write(f"### Daily detection counts for Tag {selected_tag}")

    df_tag = detections[detections["Tag"] == selected_tag].copy()
    df_tag["date"] = pd.to_datetime(df_tag["ts"]).dt.date

    daily = df_tag["date"].value_counts().sort_index()

    fig, ax = plt.subplots(figsize=(8, 3))
    ax.plot(daily.index, daily.values, marker="o")
    ax.set_title(f"Daily Detections — {selected_tag}")
    ax.set_xlabel("Date")
    ax.set_ylabel("Count")
    plt.xticks(rotation=45)
    st.pyplot(fig)

# ======================
# MODEL PAGE
# ======================

elif page == "Model":
    st.title("Migration Model (DBSCAN Results)")

    st.write("### Migration Phase Summary (all tags)")
    st.dataframe(migration_summary)

    st.write(f"### Scatter Plot of Phases — Tag {selected_tag}")

    df_tag = detections[detections["Tag"] == selected_tag].copy()
    df_tag["ts"] = pd.to_datetime(df_tag["ts"])

    fig, ax = plt.subplots(figsize=(10, 4))

    colors = {
        "Arrival": "blue",
        "Stopover": "green",
        "Departure": "red",
        "Single-Visit": "purple",
        "Movement/Noise": "gray"
    }

    for phase, group in df_tag.groupby("phase"):
        ax.scatter(group["ts"], group["hours_from_start"],
                   color=colors.get(phase, "black"),
                   label=phase, s=10)

    ax.set_title(f"DBSCAN Phase Plot — {selected_tag}")
    ax.set_xlabel("Timestamp")
    ax.set_ylabel("Hours from first detection")
    plt.xticks(rotation=45)
    ax.legend()
    st.pyplot(fig)

# ======================
# XAI PAGE
# ======================

elif page == "XAI":
    st.title("Explainable AI — Phase Behavior")

    st.write("### Feature Summary by Phase (all tags)")
    st.dataframe(phase_summary)

    st.write(f"### XAI Boxplots — Tag {selected_tag}")

    df_tag = detections[detections["Tag"] == selected_tag].copy()

    features = ["hours_from_start"]
    for col in ["sig", "slop", "runLen"]:
        if col in df_tag.columns and df_tag[col].notna().any():
            features.append(col)

    phases = df_tag["phase"].unique()

    n_features = len(features)
    fig, axes = plt.subplots(1, n_features, figsize=(4 * n_features, 4))

    if n_features == 1:
        axes = [axes]  # handle single-subplot case

    for ax, feat in zip(axes, features):
        data = [df_tag[df_tag["phase"] == ph][feat].dropna() for ph in phases]
        ax.boxplot(data, tick_labels=phases, showfliers=False)
        ax.set_title(feat)
        ax.set_ylabel(feat)
        ax.set_xticklabels(phases, rotation=30)

    st.pyplot(fig)